### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by wildstar87**
Added Rotary Encoder information, made FAN5331 replacement a little clearer.

### CODE REVIEW

**Comment by wildstar87** [comment]
Not sure if I did this right..

**Comment by valerionew** [comment]
It looks good to me

**Comment by valerionew** [comment]
This fixes #37

**Comment by valerionew** [comment]
Thank you for this contribution! It's very useful information 😄

Anytime you want to add something more, now you know how to!

**Comment by wildstar87** [comment]
Is it always a requirement to fork before doing a pull request? Or did I add an extra unnecessary step?
________________________________

**Comment by valerionew** [comment]
If you are making very small changes GitHub allows you to do them without forking. In this case, you did the right thing. 

Now that you have a fork of the repo it will stay in your repositories, so there is no need to fork it again when you will have new changes. Just make sure to do a pull request from this repo to yours before making changes so that you always start from the most recent version.

**Pull request merged**
